<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AppLearningEnglish.DataAccess/AppLearningEnglish.DataAccess.csproj" />
    <ProjectReference Include="../AppLearningEnglish.Models/AppLearningEnglish.Models.csproj" />
  </ItemGroup>

</Project>
